version: "3.5"

volumes:
  mariadb:
    name: mariadb
    driver: local #allow you to create volume and backed by dir on host machine
    driver_opts:
      device: /home/rthammat/data/mariadb # data in container will be stored here
      o: bind # specifies mount options => this case mount directly to container without any additional filesystem abstract
      type: none #it's just a regular directory on the host machine
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/rthammat/data/wordpress
      o: bind
      type: none

networks:
  inception:
    name: inception

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/.
      args:
        - MYSQL_DB_NAME=${MYSQL_DB_NAME}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    image: mariadb_image
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "3306:3306"
    restart: always
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/.
    image: wordpress_image
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "9000:9000"
    restart: always
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/.
    image: nginx_image
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    restart: always
